"""Make llm_model_id optional in chats

Revision ID: 53ec1520cd86
Revises: 71c31d8dde91
Create Date: 2025-07-30 01:51:51.036247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ec1520cd86'
down_revision = '71c31d8dde91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'llm_model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'llm_model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ### 